name: Ejecutar Auditoria de Imagenes

on:
  workflow_dispatch: # Esto permite que lo ejecutes tú manualmente con un botón

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Solo lo último para ser rápidos

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Pandas
        run: pip install pandas

      - name: Correr Auditoria
        run: python auditoria.py
