name: Despliegue Final Pages

on:
  workflow_run:
    workflows: ["Generador de Graficos"]
    types:
      - completed

# --- NUEVA SECCIÓN DE CONCURRENCIA ---
# Evita que los procesos choquen. Si uno está trabado, el nuevo lo cancela.
concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Solo descarga la última versión (optimizado)
        
      - name: Configurar Pages
        uses: actions/configure-pages@v4

      # Filtramos: Solo subimos lo necesario para la web
      # Ignoramos la carpeta 'imagenes_satelitales' para evitar los 10 min de espera
      - name: Preparar contenido web
        run: |
          mkdir public
          cp index.html public/
          cp -r monitoreo_satelital public/
          # Eliminamos la subcarpeta de imágenes pesadas del paquete de subida
          rm -rf public/monitoreo_satelital/imagenes_satelitales
        
      - name: Subir Artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public' # Sube solo la carpeta optimizada
          
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          timeout: 600000
