name: Despliegue Final Pages

on:
  workflow_run:
    workflows: ["Generador de Graficos"]
    types:
      - completed

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        
      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Preparar contenido web
        run: |
          mkdir public
          # Copiamos el index a la raíz de la carpeta pública
          cp index.html public/
          # Copiamos la carpeta de datos pero excluyendo las imágenes pesadas
          cp -r monitoreo_satelital public/
          # Borramos imágenes para no exceder el límite de Pages y acelerar el deploy
          rm -rf public/monitoreo_satelital/imagenes_satelitales
        
      - name: Subir Artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
          
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
