name: Monitor Volcanico Pro

on:
  schedule:
    - cron: '0 */3 * * *' # Se ejecuta automáticamente cada 3 horas
  workflow_dispatch: # Permite que tú le des al botón "Run workflow" manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    # PERMISO CRÍTICO: Necesario para que el bot pueda guardar archivos
    permissions:
      contents: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar Scraper
        run: python scraper.py

      - name: Guardar cambios en GitHub
        run: |
          git config --global user.name "VolcanoBot"
          git config --global user.email "bot@volcano.com"
          
          # 'add -A' es fundamental para capturar la NUEVA carpeta 'monitoreo_datos'
          git add -A
          
          # Este comando evita que falle si no hay fotos nuevas, y hace el Push
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto: Actualización Monitoreo Volcánico" && git push)
