name: Generador de Graficos

on:
  schedule:
    # Se ejecuta al minuto 5 de cada hora (Ej: 10:05, 11:05...)
    # Esto le da tiempo al scraper de terminar su corrida del minuto 00
    - cron: '5 * * * *' 
  
  workflow_dispatch: # Para que puedas forzar el dibujo cuando quieras

jobs:
  pintar_y_publicar:
    runs-on: ubuntu-latest
    # Eliminamos la condici√≥n 'if' del workflow_run anterior
