name: Monitor Volcanico Pro

on:
  schedule:
    - cron: '0 */3 * * *' # Se ejecuta automáticamente cada 3 horas
  workflow_dispatch: # Permite que tú le des al botón "Run workflow" manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    # Añadimos permisos de escritura para que el bot no falle al subir archivos
    permissions:
      contents: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4 # Versión más reciente y estable

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Ejecutar Scraper
        run: python scraper.py

      - name: Guardar cambios en GitHub
        run: |
          git config --global user.name "VolcanoBot"
          git config --global user.email "bot@volcano.com"
          
          # 'add -A' es fundamental para capturar las carpetas de fecha/hora
          git add -A
          
          # Este comando evita que el proceso falle si no hay fotos nuevas ese día
          git diff --quiet && git diff --staged --quiet || (git commit -m "Captura Triple Sensor: $(date +'%Y-%m-%d %H:%M')" && git push)
