- name: Ejecutar Scraper
        run: python scraper.py

      # --- HEMOS ELIMINADO EL VISUALIZADOR DE AQUÍ ---

      - name: Guardar cambios en GitHub
        run: |
          git config --global user.name "VolcanoBot"
          git config --global user.email "bot@volcano.com"
          git add -A
          if ! git diff --quiet --staged; then
            git commit -m "Auto: Sincronización de datos e imágenes"
            git pull origin main --rebase -X ours
            git push origin main
          fi
